# Generated by Django 3.2.9 on 2021-11-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.TextField(default='')),
                ('ciudad', models.TextField(default='')),
                ('barrio', models.TextField(default='')),
                ('direccion', models.TextField(default='')),
                ('estrato', models.IntegerField(default=0)),
                ('codigoPostal', models.IntegerField(default=0)),
                ('CFN', models.IntegerField(default=0)),
                ('PrimerNombre', models.TextField(default='')),
                ('SegundoNombre', models.TextField(default='', null=True)),
                ('PrimerApellido', models.TextField(default='')),
                ('SegundoApellido', models.TextField(default='')),
                ('edad', models.IntegerField(default=0)),
                ('profesion', models.TextField(default='')),
                ('area', models.IntegerField(default=0)),
                ('tipo', models.TextField(default='')),
                ('agua', models.TextField(default='No')),
                ('luz', models.TextField(default='No')),
                ('gas', models.TextField(default='No')),
                ('internet', models.TextField(default='No')),
                ('computador', models.TextField(default='No')),
                ('propia', models.TextField(default='No')),
                ('feedback', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.TextField(default='')),
                ('ciudad', models.TextField(default='')),
                ('barrio', models.TextField(default='')),
                ('direccion', models.TextField(default='')),
                ('estrato', models.IntegerField(default=0)),
                ('codigoPostal', models.IntegerField(default=0)),
                ('CFN', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.TextField(default='')),
                ('SegundoNombre', models.TextField(default='', null=True)),
                ('PrimerApellido', models.TextField(default='')),
                ('SegundoApellido', models.TextField(default='')),
                ('edad', models.IntegerField(default=0)),
                ('profesion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tipo', models.TextField(default='')),
                ('agua', models.TextField(default='No')),
                ('luz', models.TextField(default='No')),
                ('gas', models.TextField(default='No')),
                ('internet', models.TextField(default='No')),
                ('computador', models.TextField(default='No')),
                ('propia', models.TextField(default='No')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCenso.direccion')),
                ('claveFeedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCenso.feedback')),
                ('clavePersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCenso.persona')),
                ('claveVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCenso.vivienda')),
            ],
        ),
    ]
