# Generated by Django 3.2.9 on 2021-11-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCenso', '0002_alter_vivienda_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='area',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
