# Generated by Django 3.2.9 on 2021-11-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCenso', '0004_alter_datos_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='CFN',
            field=models.CharField(default='', max_length=30),
        ),
    ]
